version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "8080:15672"
      - "5672:5672"

  couchbase:
    image: couchbase
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis-etl:
    build:
      context: ./RedisETL
    depends_on:
      - couchbase
      - redis
    volumes:
      - ./configuration.yaml:/app/configuration.yaml

  rabbit-producer:
    build:
      context: ./RabbitProducer
    depends_on:
      - rabbitmq
    volumes:
      - ./configuration.yaml:/app/configuration.yaml

  rabbit-consumer:
    build:
      context: ./RabbitConsumer
    depends_on:
      - rabbitmq
      - couchbase
    volumes:
      - ./configuration.yaml:/app/configuration.yaml
